//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18051
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/networking/WLAN/profile/v1")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.microsoft.com/networking/WLAN/profile/v1", IsNullable=false)]
public partial class WLANProfile {
    
    private string nameField;
    
    private WLANProfileSSIDConfig[] sSIDConfigField;
    
    private WLANProfileConnectionType connectionTypeField;
    
    private WLANProfileConnectionMode connectionModeField;
    
    private bool connectionModeFieldSpecified;
    
    private bool autoSwitchField;
    
    private bool autoSwitchFieldSpecified;
    
    private WLANProfileMSM mSMField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <comentarios/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("SSIDConfig")]
    public WLANProfileSSIDConfig[] SSIDConfig {
        get {
            return this.sSIDConfigField;
        }
        set {
            this.sSIDConfigField = value;
        }
    }
    
    /// <comentarios/>
    public WLANProfileConnectionType connectionType {
        get {
            return this.connectionTypeField;
        }
        set {
            this.connectionTypeField = value;
        }
    }
    
    /// <comentarios/>
    public WLANProfileConnectionMode connectionMode {
        get {
            return this.connectionModeField;
        }
        set {
            this.connectionModeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool connectionModeSpecified {
        get {
            return this.connectionModeFieldSpecified;
        }
        set {
            this.connectionModeFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public bool autoSwitch {
        get {
            return this.autoSwitchField;
        }
        set {
            this.autoSwitchField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool autoSwitchSpecified {
        get {
            return this.autoSwitchFieldSpecified;
        }
        set {
            this.autoSwitchFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public WLANProfileMSM MSM {
        get {
            return this.mSMField;
        }
        set {
            this.mSMField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/networking/WLAN/profile/v1")]
public partial class WLANProfileSSIDConfig {
    
    private WLANProfileSSIDConfigSSID[] sSIDField;
    
    private bool nonBroadcastField;
    
    private bool nonBroadcastFieldSpecified;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("SSID")]
    public WLANProfileSSIDConfigSSID[] SSID {
        get {
            return this.sSIDField;
        }
        set {
            this.sSIDField = value;
        }
    }
    
    /// <comentarios/>
    public bool nonBroadcast {
        get {
            return this.nonBroadcastField;
        }
        set {
            this.nonBroadcastField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nonBroadcastSpecified {
        get {
            return this.nonBroadcastFieldSpecified;
        }
        set {
            this.nonBroadcastFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/networking/WLAN/profile/v1")]
public partial class WLANProfileSSIDConfigSSID {
    
    private byte[] hexField;
    
    private string nameField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
    public byte[] hex {
        get {
            return this.hexField;
        }
        set {
            this.hexField = value;
        }
    }
    
    /// <comentarios/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/networking/WLAN/profile/v1")]
public enum WLANProfileConnectionType {
    
    /// <comentarios/>
    IBSS,
    
    /// <comentarios/>
    ESS,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/networking/WLAN/profile/v1")]
public enum WLANProfileConnectionMode {
    
    /// <comentarios/>
    auto,
    
    /// <comentarios/>
    manual,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/networking/WLAN/profile/v1")]
public partial class WLANProfileMSM {
    
    private WLANProfileMSMConnectivity connectivityField;
    
    private WLANProfileMSMSecurity securityField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <comentarios/>
    public WLANProfileMSMConnectivity connectivity {
        get {
            return this.connectivityField;
        }
        set {
            this.connectivityField = value;
        }
    }
    
    /// <comentarios/>
    public WLANProfileMSMSecurity security {
        get {
            return this.securityField;
        }
        set {
            this.securityField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/networking/WLAN/profile/v1")]
public partial class WLANProfileMSMConnectivity {
    
    private WLANProfileMSMConnectivityPhyType[] phyTypeField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("phyType")]
    public WLANProfileMSMConnectivityPhyType[] phyType {
        get {
            return this.phyTypeField;
        }
        set {
            this.phyTypeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/networking/WLAN/profile/v1")]
public enum WLANProfileMSMConnectivityPhyType {
    
    /// <comentarios/>
    a,
    
    /// <comentarios/>
    b,
    
    /// <comentarios/>
    g,
    
    /// <comentarios/>
    n,
    
    /// <comentarios/>
    ac,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/networking/WLAN/profile/v1")]
public partial class WLANProfileMSMSecurity {
    
    private WLANProfileMSMSecurityAuthEncryption authEncryptionField;
    
    private WLANProfileMSMSecurityPMKCacheMode pMKCacheModeField;
    
    private bool pMKCacheModeFieldSpecified;
    
    private string pMKCacheTTLField;
    
    private string pMKCacheSizeField;
    
    private WLANProfileMSMSecurityPreAuthMode preAuthModeField;
    
    private bool preAuthModeFieldSpecified;
    
    private string preAuthThrottleField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <comentarios/>
    public WLANProfileMSMSecurityAuthEncryption authEncryption {
        get {
            return this.authEncryptionField;
        }
        set {
            this.authEncryptionField = value;
        }
    }
    
    /// <comentarios/>
    public WLANProfileMSMSecurityPMKCacheMode PMKCacheMode {
        get {
            return this.pMKCacheModeField;
        }
        set {
            this.pMKCacheModeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PMKCacheModeSpecified {
        get {
            return this.pMKCacheModeFieldSpecified;
        }
        set {
            this.pMKCacheModeFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string PMKCacheTTL {
        get {
            return this.pMKCacheTTLField;
        }
        set {
            this.pMKCacheTTLField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string PMKCacheSize {
        get {
            return this.pMKCacheSizeField;
        }
        set {
            this.pMKCacheSizeField = value;
        }
    }
    
    /// <comentarios/>
    public WLANProfileMSMSecurityPreAuthMode preAuthMode {
        get {
            return this.preAuthModeField;
        }
        set {
            this.preAuthModeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool preAuthModeSpecified {
        get {
            return this.preAuthModeFieldSpecified;
        }
        set {
            this.preAuthModeFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string preAuthThrottle {
        get {
            return this.preAuthThrottleField;
        }
        set {
            this.preAuthThrottleField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/networking/WLAN/profile/v1")]
public partial class WLANProfileMSMSecurityAuthEncryption {
    
    private WLANProfileMSMSecurityAuthEncryptionAuthentication authenticationField;
    
    private WLANProfileMSMSecurityAuthEncryptionEncryption encryptionField;
    
    private bool useOneXField;
    
    private bool useOneXFieldSpecified;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <comentarios/>
    public WLANProfileMSMSecurityAuthEncryptionAuthentication authentication {
        get {
            return this.authenticationField;
        }
        set {
            this.authenticationField = value;
        }
    }
    
    /// <comentarios/>
    public WLANProfileMSMSecurityAuthEncryptionEncryption encryption {
        get {
            return this.encryptionField;
        }
        set {
            this.encryptionField = value;
        }
    }
    
    /// <comentarios/>
    public bool useOneX {
        get {
            return this.useOneXField;
        }
        set {
            this.useOneXField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool useOneXSpecified {
        get {
            return this.useOneXFieldSpecified;
        }
        set {
            this.useOneXFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/networking/WLAN/profile/v1")]
public enum WLANProfileMSMSecurityAuthEncryptionAuthentication {
    
    /// <comentarios/>
    open,
    
    /// <comentarios/>
    shared,
    
    /// <comentarios/>
    WPA,
    
    /// <comentarios/>
    WPAPSK,
    
    /// <comentarios/>
    WPA2,
    
    /// <comentarios/>
    WPA2PSK,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/networking/WLAN/profile/v1")]
public enum WLANProfileMSMSecurityAuthEncryptionEncryption {
    
    /// <comentarios/>
    none,
    
    /// <comentarios/>
    WEP,
    
    /// <comentarios/>
    TKIP,
    
    /// <comentarios/>
    AES,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/networking/WLAN/profile/v1")]
public enum WLANProfileMSMSecurityPMKCacheMode {
    
    /// <comentarios/>
    disabled,
    
    /// <comentarios/>
    enabled,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/networking/WLAN/profile/v1")]
public enum WLANProfileMSMSecurityPreAuthMode {
    
    /// <comentarios/>
    disabled,
    
    /// <comentarios/>
    enabled,
}
